### ISSUE TITLE
定时重启

### ISSUE THREAD

**Issue by vmos0** [vipshmily/Padavan-3.4-KVR#6]
大佬你好请问无线中继模式下定时重启是否有效？

**Comment by vipshmily** [comment]
正常情况下是有效的

**Comment by Fyg369** [comment]
> 正常情况下是有效的
恩山论坛有大佬修复过需要WAN口连接网络才有用，但是我用的无线中继模式貌似没效果，另外请教下我克隆您的源码仓库本地编译始终失败，不是依赖问题就是编译器问题，我是按照这位大佬https://github.com/chongshengB/rt-n56u教程操作的，有时间麻烦大佬回复指点下谢谢啦！我用的是虚拟机乌班图编译

**Comment by vmos0** [comment]
> 正常情况下是有效的

恩山论坛有大佬修复过需要WAN口连接网络才有用，但是我用的无线中继模式貌似没效果，另外请教下我克隆您的源码仓库本地编译始终失败，不是依赖问题就是编译器问题，我是按照这位大佬教程操作的
https://github.com/chongshengB/rt-n56u
有时间麻烦大佬回复指点下谢谢啦！我用的是虚拟机乌班图编译的RM2100
